com.fasterxml.jackson.*:* = 2.20.0
com.fasterxml.jackson.core:jackson-annotations = 2.20
com.google.guava:guava = 33.5.0-jre
com.netflix.feign:feign-*= 8.18.0
com.palantir.conjure:conjure = 4.52.0
com.palantir.conjure.java:* = 8.59.0
com.palantir.conjure.java.api:test-utils = 2.65.0
com.palantir.conjure.java.runtime:* = 8.25.0
com.palantir.conjure.typescript:conjure-typescript = 5.11.0
io.undertow:* = 2.2.38.Final
org.assertj:assertj-core = 3.27.6
org.immutables:* = 2.11.6
org.junit.jupiter:* = 6.0.0
org.junit.platform:* = 6.0.0
org.slf4j:* = 2.0.17
