com.fasterxml.jackson.*:* = 2.21.1
com.fasterxml.jackson.core:jackson-annotations = 2.21
com.google.guava:guava = 33.5.0-jre
com.netflix.feign:feign-*= 8.18.0
com.palantir.conjure:conjure = 4.55.0
com.palantir.conjure.java:* = 8.75.0
com.palantir.conjure.java.api:test-utils = 2.71.0
com.palantir.conjure.java.runtime:* = 8.33.0
com.palantir.conjure.typescript:conjure-typescript = 5.17.0
io.undertow:* = 2.2.38.Final
org.assertj:assertj-core = 3.27.7
org.immutables:* = 2.12.1
org.junit.jupiter:* = 6.0.3
org.junit.platform:* = 6.0.3
org.slf4j:* = 2.0.17
